### ISSUE TITLE
Possible encoding problem in task list

### ISSUE THREAD

**Issue by garaik-moon42** [gondoni/timetracker#1]
After sending a GET request to the /tasks endpoint, the result JSON contains strange characters, possible due to an encoding problem. It is worth a check.
`[{"id":1,"code":"F11","description":"Feladat1, ami fontos","project":{"id":1,"code":"PR1","name":"Projekt1","description":"Fontos projekt"}},{"id":2,"code":"F12","description":"Feladat2, ami sÃ¼rgÅ‘s","project":{"id":1,"code":"PR1","name":"Projekt1","description":"Fontos projekt"}}]`

**Comment by gondoni** [comment]
Solved with converting the character set of the initial sql file.
